### ISSUE TITLE
SE3 covariances

### ISSUE THREAD

**Issue by g-ferrer-sk** [MobileRoboticsSkoltech/mrob#61]
new class including covariance propagation

**Comment by nosmokingsurfer** [comment]
- [ ] SE3cov class in cpp
- [ ] variable names according to the guide
- [ ] instructions for local build
- [ ] cpp class comments in doxygen format
- [ ] unit tests for SE3cov class usgin catch2 module
- [ ] python bindings
- [ ] python examples
- [ ] python visualization functions

**Comment by g-ferrer-sk** [comment]
related to pull request #82
