### ISSUE TITLE
Unit test

### ISSUE THREAD

**Issue by g-ferrer-sk** [MobileRoboticsSkoltech/mrob#71]
ideally, minimal external dependency

**Comment by nosmokingsurfer** [comment]
Hi, Gonzalo, @g-ferrer-sk 

I've made a separate branch for unit test trials. At the moment I just added catch2 header into the examples folder and rewrote tests for the ```mrob::SE3``` class, so you can just compare side by side with the previous SE3 example project.

I use VSCode as IDE and use C++ TestMate plugin to have a separate unit test panel:
![Screenshot from 2021-06-30 17-08-00](https://user-images.githubusercontent.com/22825575/123975025-be55a280-d9c5-11eb-8fa4-fe83511a7d58.png)
The plugin suggests that a unit test must have a name with the pattern **"test.*"** to automatically reveal it and add it to the list.

For other IDE's like Visual Studio there also should be tools for unit test reveal and running.

The questions are:
1. If catch2 fits the requirements for testing?
2. What is a good place to put the catch.hpp header file?
3. Should I also add the Cmake flag BUILD_TESTS or just build them by default at the moment?

**Comment by nosmokingsurfer** [comment]
closed in #78 PR
